[database]
DB_HOST="aws-1-ap-southeast-1.pooler.supabase.com"
DB_PORT=6543
DB_NAME="postgres"
USERNAME_CREDENTIALS="postgres.dejmorrzxvnpkttlkoad"
PASSWORD_CREDENTIALS="Asepkasep21"

[api]
OPENROUTER_API_KEY="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"